spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:${CLEARDB_MAUVE_URL:mysql://localhost:3306/dev_put?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
        username: root
        password: "00400040"
    jpa:
        hibernate.ddl-auto: none
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    mail:
        host: smtp.yandex.ru
        username: zubayr.service@yandex.ru
        password: service2020
        port: 465
        protocol: smtps
        debag: true
    mvc:
      static-path-pattern: file:src/main/resources/static/img/


host: ${HOST_URL:http://localhost}
server:
    port: ${PORT:8080}


captcha.lifetime: 1

